Feature/issue 1
f-lab-edu/yeogi-moim pull request #2
Opened 2024-10-02 10:01 UTC by Kimjipang

- 회원관리 API 구현
- 세션 기반 인증 구현

2024-10-03 06:31 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백 확인 부탁드려요!

2024-10-03 06:31 UTC, f-lab-moony commented on src/main/java/yeogi/moim/config/SecurityConfig.java
> +@RequiredArgsConstructor
`@RequiredArgsConstructor` 는 무슨 역할을 하나요 ?
여기에서는 어떤 의미가 있을까요 ?

2024-10-03 06:31 UTC, f-lab-moony commented on src/main/java/yeogi/moim/config/SecurityConfig.java
> +    public UserDetailsService userDetailsService(MemberRepository memberRepository) {
service랑 entity를 구현체를 따로 만들어주는게 좋을 것 같아요 ~

2024-10-03 06:31 UTC, f-lab-moony commented on src/main/java/yeogi/moim/member/controller/AuthController.java
> +    public String login() {
요거 html 서빙하려고 만드신건가요 ?

2024-10-03 06:31 UTC, f-lab-moony commented on src/main/java/yeogi/moim/member/controller/MemberController.java
> +@RequiredArgsConstructor
`@RequiredArgsConstructor`도 그렇고, 롬복에서 쓰면 위험한 어노테이션들과 왜그런지 한번 찾아보시면 좋을 것 같아요 ~

2024-10-03 06:31 UTC, f-lab-moony commented on src/main/java/yeogi/moim/member/controller/MemberController.java
> +@RequestMapping("/api/member")
컨트롤러의 토픽이 되는 도메인은 복수형으로 쓰는편이에요!

2024-10-03 06:31 UTC, f-lab-moony commented on src/main/java/yeogi/moim/member/controller/MemberController.java
> +    public ResponseEntity<MemberResponseDto> registerMember(@RequestBody MemberRequestDto memberRequestDto) {
여기는 어차피 성공한 응답들이 나갈거라 ResponseEntity로 안감싸줘도 될 것 같아요 ~
어차피 클라이언트에서 보는건 200인지 아닌지라서요

2024-10-03 06:31 UTC, f-lab-moony commented on src/main/java/yeogi/moim/member/controller/MemberController.java
> +    @GetMapping("/{id}")
id는 너무 범용적인 표현이라 memberId처럼 명시적으로 써주는게 좋을 것 같아요 ~

2024-10-03 06:31 UTC, f-lab-moony commented on src/main/java/yeogi/moim/member/dto/MemberRequestDto.java
> +public class MemberRequestDto {
Request랑 Dto는 비슷한 표현이라 하나만 써도 될 것 같아요 ~ 저는 개인적으로 Dto라는 표현을 클래스 이름에 두는건 별로 안좋아하긴 합니다!

2024-10-03 06:31 UTC, f-lab-moony commented on src/main/java/yeogi/moim/member/dto/MemberResponseDto.java
> +    public MemberResponseDto(Member member) {
요런거 정적 패토리 메서드로 빼면 어떤 장점이 있을까요 ?

2024-10-03 06:31 UTC, f-lab-moony commented on src/main/java/yeogi/moim/member/entity/Member.java
> +    public void update(String email, String username, String password) {
변경이력이 좀 남아야 될 것 같은데, 요런게 실제 서비스 운영할때는 누가 했는지가 중요한 부분이라 데이터에 따라 신경을 써주는게 좋아요!
JPA Auditing에 대해서 한번 찾아보시면 좋을 것 같습니다 ~

2024-10-03 06:31 UTC, f-lab-moony commented on src/main/java/yeogi/moim/member/service/MemberService.java
> +        Member member = new Member(
요런건 Request가 책임을 가져가도 되지 않을까요 ?

2024-10-03 06:31 UTC, f-lab-moony commented on src/main/java/yeogi/moim/member/service/MemberService.java
> +    public MemberResponseDto registerMember(MemberRequestDto memberRequestDto) {
서비스에 `@Transactional`을 붙여주지 않으면 어떤 일이 일어날까요 ?

2024-10-03 06:31 UTC, f-lab-moony commented on src/main/java/yeogi/moim/member/service/MemberService.java
> +        for (Member member : members) {
요거 Stream API를 이용해보면 좋을 것 같아요 ~

2024-10-04 07:37 UTC, Kimjipang commented on src/main/java/yeogi/moim/config/SecurityConfig.java
> +@RequiredArgsConstructor
의존성 주입을 생성자 주입 방식으로 할 때 활용되는 어노테이션입니다. 해당 코드에서는 의미가 없는데, 삭제를 안 한 것 같습니다 😲

감사합니다 멘토님 ~!

2024-10-04 07:39 UTC, Kimjipang commented on src/main/java/yeogi/moim/config/SecurityConfig.java
> +    public UserDetailsService userDetailsService(MemberRepository memberRepository) {
질문이 있습니다 멘토님 !

- `UserDetailsServiceImpl` 과 같은 방식으로 활용하는 것을 말씀하시는 걸까요??

2024-10-04 07:39 UTC, Kimjipang commented on src/main/java/yeogi/moim/member/controller/AuthController.java
> +    public String login() {
맞습니다 !

2024-10-04 07:40 UTC, Kimjipang commented on src/main/java/yeogi/moim/member/controller/MemberController.java
> +@RequiredArgsConstructor
넵 ! 찾아보겠습니다 멘토님 :)

2024-10-04 07:42 UTC, Kimjipang commented on src/main/java/yeogi/moim/member/controller/MemberController.java
> +@RequestMapping("/api/member")
넵!! 수정하겠습니다 :)

2024-10-04 07:42 UTC, Kimjipang commented on src/main/java/yeogi/moim/member/dto/MemberResponseDto.java
> +    public MemberResponseDto(Member member) {
정적 팩토리 메서드로 뺀다는 말씀이 이해가 잘 안 되어서 찾아보고 다시 코멘트 달겠습니다 멘토님 !

2024-10-04 07:43 UTC, Kimjipang commented on src/main/java/yeogi/moim/member/entity/Member.java
> +    public void update(String email, String username, String password) {
아 JPA Auditing 추가해두겠습니다!!

2024-10-04 07:43 UTC, Kimjipang commented on src/main/java/yeogi/moim/member/service/MemberService.java
> +        Member member = new Member(
이 부분 생각해보고 다시 코멘트 달겠습니다 멘토님 ~!

2024-10-04 07:46 UTC, Kimjipang commented on src/main/java/yeogi/moim/member/service/MemberService.java
> +    public MemberResponseDto registerMember(MemberRequestDto memberRequestDto) {
데이터 일관성 등이 지켜지지 않을 수 있게 되고, 원하는 처리가 정상적으로 이루어지지 않게 될 수 있습니다! 수정하겠습니다 멘토님 ~!

2024-10-04 07:47 UTC, Kimjipang commented on src/main/java/yeogi/moim/member/service/MemberService.java
> +        for (Member member : members) {
넵 ㅎ.ㅎ 한 번 사용해보겠습니다!

2024-10-04 10:31 UTC, Kimjipang commented on src/main/java/yeogi/moim/member/controller/MemberController.java
> +    public ResponseEntity<MemberResponseDto> registerMember(@RequestBody MemberRequestDto memberRequestDto) {
무슨 뜻인지 이해가 되지 않아 찾아보았는데 의도하신 것이 맞는지 확인 부탁드리겠습니다 !

ResponseEntity를 활용하는 이유는 응답 본분이나 상태 코드를 바꾸고자 함인데, registerMember 메서드의 성격상 member 객체가 정상적으로 만들어졌는지 아닌지만 클라이언트측에서 확인하면 되기 때문에 ResponseEntity를 사용하지 않아도 될 거 같다는 말씀이실까요??

2024-10-04 10:31 UTC, Kimjipang commented on src/main/java/yeogi/moim/member/controller/MemberController.java
> +    @GetMapping("/{id}")
네 ! 수정하겠습니다 : )

2024-10-04 10:34 UTC, Kimjipang commented on src/main/java/yeogi/moim/member/dto/MemberRequestDto.java
> +public class MemberRequestDto {
멘토님 ! 현재 MemberRequestDto와 MemberResposneDto로 구분지었는데, MemberRequest & MemberResponse 라고 클래스 네이밍을 해주는 편이 더 좋을까요?

2024-10-05 14:59 UTC, f-lab-moony commented on src/main/java/yeogi/moim/config/SecurityConfig.java
> +    public UserDetailsService userDetailsService(MemberRepository memberRepository) {
UserDetail이랑 UserDetailService를 상속받는 구현체를 따로 만들어서 고거 사용하게 하는게 좋을 것 같다는 의미였습니다~

2024-10-05 14:59 UTC, f-lab-moony commented on src/main/java/yeogi/moim/member/controller/AuthController.java
> +    public String login() {
`AuthController` 라는 이름이 안맞는 것 같아요 ~ 그리고 정적 리소스 서빙이면 컨트롤러 따로 없어도 되지 않나요 ?

2024-10-05 15:00 UTC, f-lab-moony commented on src/main/java/yeogi/moim/member/dto/MemberResponseDto.java
> +    public MemberResponseDto(Member member) {
`public static` 으로 객체를 만들어주는 메서드를 만드는 패턴이 있어요 ~

2024-10-07 13:39 UTC, Kimjipang commented on src/main/java/yeogi/moim/member/controller/AuthController.java
> +    public String login() {
프로젝트 생성할 때 thymeleaf 의존성 넣었어서 templates 폴더에 html 생성했습니다! 정적 리소스 서빙하도록 변경해야 할까요?

2024-10-09 06:39 UTC, f-lab-moony commented on src/main/java/yeogi/moim/member/dto/MemberResponse.java
> +    public static MemberResponse from(Member member) {
```return new MemberResponse(member.getId(), member.getUsername(), member.getEmail() ...);```

2024-10-11 08:41 UTC, f-lab-moony approved these changes
고생 많으셨습니다!
요건 머지 하도록 할게요 ~

2024-10-11 08:41 UTC, f-lab-moony commented on src/main/java/yeogi/moim/member/dto/MemberResponse.java
> +    private MemberResponse(Member member) {
```private MemberResponse(Long memberId, String username, String email...) {}```

2024-10-11 08:41 UTC, f-lab-moony commented on src/main/java/yeogi/moim/member/dto/MemberResponse.java
> +    private Long member_id;
memberId

2024-10-11 08:41 UTC, merged