Feature/issue 3
f-lab-edu/yeogi-moim pull request #4
Opened 2024-10-11 19:02 UTC by Kimjipang

- 스터디 모임(Gathering) CRUD API
- Member 엔티티와 Gathering 엔티티 OneToMany 연관관계 매핑

2024-10-16 04:29 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백 확인 부탁드려요!

2024-10-16 04:29 UTC, f-lab-moony commented on src/main/java/yeogi/moim/gathering/controller/GatheringController.java
> +    public List<GatheringResponse> getRecentGatheringList() {
`/search`같은 엔드포인트로 통일

2024-10-16 04:29 UTC, f-lab-moony commented on src/main/java/yeogi/moim/gathering/entity/Gathering.java
> +    public void update(String title, String description, int totalPersonnel) {
요거 말씀드린거처럼 수정자도 같이 저장되게 해주시면 좋을 것 같아요 ~

2024-10-16 04:29 UTC, f-lab-moony commented on src/main/java/yeogi/moim/gathering/repository/GatheringRepository.java
> +    @Query("SELECT g FROM Gathering g WHERE g.totalPersonnel != g.currentPersonnel")
요것도 QueryDSL로 한번 바꿔보시죠!

2024-10-16 04:29 UTC, f-lab-moony commented on src/main/java/yeogi/moim/gathering/service/GatheringService.java
> +        gatheringRepository.save(gathering);
JPA의 더티체킹에 대해 찾아보시면 좋을 것 같아요 ~

2024-10-16 04:29 UTC, f-lab-moony commented on src/main/java/yeogi/moim/participant/dto/ParticipantResponse.java
> +    private double rating;
요런거 Wrapping Class로 선언해주세요 ~

2024-10-16 04:29 UTC, f-lab-moony commented on src/main/java/yeogi/moim/participant/entity/Participant.java
> +import jakarta.persistence.*;
IDE 설정에 요거 쓰는거만 명확하게 임포트하게 바꿀 수 있는데 풀어서 임포트하도록 해주는게 좋아요 ~ 간혹 클래스명이 같거나 할때 잘못된 클래스를 사용하게 될 수도 있어요

2024-10-22 12:40 UTC, f-lab-moony approved these changes
고생 많으셨습니다!
피드백 확인 부탁드리고 요번 PR은 머지해둘게요 ~

2024-10-22 12:40 UTC, f-lab-moony commented on src/main/java/yeogi/moim/common/BaseAuditableEntity.java
> +    private String createdBy;
작성자, 수정자 같은 정보는 작성일, 수정일과 붙어다녀서 그냥 하나로 몰아도 될 것 같아요 ?

2024-10-22 12:40 UTC, f-lab-moony commented on src/main/java/yeogi/moim/gathering/controller/GatheringController.java
> +            @RequestParam(required = false) Category category,
RequestBody를 사용하시는게 더 좋을 것 같아요 ~ 아마 조회라 Get 메서드로 만들려고 그러셨을 것 같은데, 조회 요청에서 POST 메서드도 종종 사용하니 괜찮습니다 ~

2024-10-22 12:40 UTC, f-lab-moony commented on src/main/java/yeogi/moim/gathering/dto/GatheringRequest.java
> +    private Integer totalPersonnel;
👍

2024-10-22 12:40 UTC, f-lab-moony commented on src/main/java/yeogi/moim/gathering/repository/GatheringRepositoryCustomImpl.java
> +    private BooleanExpression categoryEq(Category category) {
ifNotEquals 같은 공통 메서드를 만들면 재사용이 가능할 것 같아요 ~

2024-10-22 12:40 UTC, f-lab-moony commented on src/main/java/yeogi/moim/security/AuditorAwareImpl.java
> +    public Optional<String> getCurrentAuditor() {
요건 로컬테스트용으로 만드신걸까요 ?

2024-10-22 12:40 UTC, merged

2024-10-22 14:15 UTC, Kimjipang reviewed
BaseAuditableEntity로 빼지 말고 하나의 클래스로 몰아도 된다는 말씀이신가요??

2024-10-22 14:15 UTC, Kimjipang commented on src/main/java/yeogi/moim/participant/service/ParticipantService.java
> +    private final MemberRepository memberRepository;
멘토님 질문 남깁니다 !

멘토링 때 말씀 주셨던 파사드 패턴 방식으로 수정하려고 하는데요!

MemberService랑 GatheringService로 수정해서 각 service 내 메서드로 member 객체와 gathering 객체를 가져오려고 합니다!

근데, 각 service 내에는 반환 타입이 MemberResponse와 GatheringResponse 여서 `participantRequest.toEntity(member,gathering);` 으로 Participant 객체 생성이 불가합니다. 

이걸 해결해보고자 제가 생각한 방법이 하나인데, 피드백 부탁드리겠습니다. 
**방법 1.
MemberService와 GatheringService 내에 각각 Member와 Gathering을 반환타입으로 하는 메서드를 만들어 그걸 ParticipantService에서 호출하는 방법**

2024-10-22 14:15 UTC, Kimjipang commented on src/main/java/yeogi/moim/gathering/controller/GatheringController.java
> +            @RequestParam(required = false) Category category,
넵!! 멘토님 근데 혹시 RequestBody로 사용해야 하는 이유가 있을까요?

2024-10-22 14:15 UTC, Kimjipang commented on src/main/java/yeogi/moim/gathering/repository/GatheringRepositoryCustomImpl.java
> +    private BooleanExpression categoryEq(Category category) {
넵 반영해보겠습니다 ~!

2024-10-22 14:15 UTC, Kimjipang commented on src/main/java/yeogi/moim/security/AuditorAwareImpl.java
> +    public Optional<String> getCurrentAuditor() {
수정자 넣으려고 한 코드인데, 잘못 작성된 건가요 ?!

2024-10-22 14:15 UTC, Kimjipang commented on src/main/java/yeogi/moim/common/BaseAuditableEntity.java
> +    private String createdBy;
BaseAuditableEntity로 빼지 말고 하나의 클래스로 몰아도 된다는 말씀이신가요??