Feature/issue 5
f-lab-edu/yeogi-moim pull request #6
Opened 2024-11-04 13:17 UTC by Kimjipang

2024-11-09 14:25 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
코멘트 확인 부탁드려요!

2024-11-09 14:25 UTC, f-lab-moony commented on src/main/java/yeogi/moim/gathering/dto/SearchGatheringRequest.java
> +    private boolean orderBy;
이건 뭘 기준으로 정렬할지 어떻게 알 수 있는걸까요 ?

2024-11-09 14:25 UTC, f-lab-moony commented on src/main/java/yeogi/moim/gathering/dto/SearchGatheringRequest.java
> +    private Category category;
필터랑 정렬이 구분되면 좋을 것 같아요 ~

2024-11-09 14:25 UTC, f-lab-moony commented on src/main/java/yeogi/moim/gathering/entity/Gathering.java
> +    public void update(String title, String description, Integer totalPersonnel, Category category) {
JPA의 dirtycheck 시 업데이트가 어떻게 수행되는지 알고 계실까요 ?

추가로, null로 업데이트 되는걸 원치 않으시는거라면, 유효성검사를 통해 예외를 던져줘야 할 것 같아요

2024-11-09 14:25 UTC, f-lab-moony commented on src/main/java/yeogi/moim/gathering/service/GatheringService.java
> +        if (gathering.getTotalPersonnel() <= gathering.getCurrentPersonnel()) {
거의 동일한 시간에 서로 다른 유저가 참여를 하게되면 아래 로직이 안전하게 동작할 수 있을까요 ?

2024-11-09 14:25 UTC, f-lab-moony commented on src/main/java/yeogi/moim/gathering/service/RegisterGatheringService.java
> +        gatheringRepository.save(gathering);
이것도 서비스 이용해주시는게 어떨까요 ?

2024-11-09 14:25 UTC, f-lab-moony commented on src/main/java/yeogi/moim/participant/service/ParticipantService.java
> +    public ParticipantResponse registerMemberParticipant(ParticipantRequest participantRequest) {
아 승인이 따로 있군요! 그럼 위에 참여신청은 실제 참여가 완료된 건 아닌걸까요 ?

2024-11-10 04:42 UTC, Kimjipang commented on src/main/java/yeogi/moim/gathering/dto/SearchGatheringRequest.java
> +    private boolean orderBy;
사용자 입장에서 어떤 걸 입력으로 요청해야 될지 모르지 않냐는 말씀이신가요?

2024-11-10 04:42 UTC, Kimjipang commented on src/main/java/yeogi/moim/gathering/dto/SearchGatheringRequest.java
> +    private Category category;
필터 request랑 정렬 request를 말씀하시는 건가요?

2024-11-10 04:42 UTC, Kimjipang commented on src/main/java/yeogi/moim/gathering/entity/Gathering.java
> +    public void update(String title, String description, Integer totalPersonnel, Category category) {
JPA가 더티체킹으로 변경 사항이 생기면 save 메서드를 하지 않아도 자동으로 해준다는 것은 알고 있는데 어떻게 수행되는지는 모르고 있어서 한 번 학습해보겠습니다.

2024-11-10 04:42 UTC, Kimjipang commented on src/main/java/yeogi/moim/gathering/service/GatheringService.java
> +        if (gathering.getTotalPersonnel() <= gathering.getCurrentPersonnel()) {
잘 모르지만 그게 동시성 제어인가요?

2024-11-10 04:42 UTC, Kimjipang commented on src/main/java/yeogi/moim/gathering/service/RegisterGatheringService.java
> +        gatheringRepository.save(gathering);
넵, 알겠습니다 !!

2024-11-10 04:42 UTC, Kimjipang commented on src/main/java/yeogi/moim/participant/service/ParticipantService.java
> +    public ParticipantResponse registerMemberParticipant(ParticipantRequest participantRequest) {
"위에 참여신청"이 registerMemberParticipant() 를 말씀하시는 건가요 ?!

2024-11-10 13:47 UTC, f-lab-moony commented on src/main/java/yeogi/moim/gathering/dto/SearchGatheringRequest.java
> +    private boolean orderBy;
정렬 방식이 최신순이나 뭐 다른게 있을수도 있는데 요거 하나로는 구분이 안될 것 같아서 여쭤봤어요!

2024-11-10 13:48 UTC, f-lab-moony commented on src/main/java/yeogi/moim/gathering/dto/SearchGatheringRequest.java
> +    private Category category;
요청 내에 필터에 대한 내용인지 정렬에 대한 내용인지 구분이 가능하면 좋을 것 같아요 ~
이럴땐 어떤 방법을 쓰는게 좋을까요 ?

2024-11-10 13:49 UTC, f-lab-moony commented on src/main/java/yeogi/moim/gathering/service/GatheringService.java
> +        if (gathering.getTotalPersonnel() <= gathering.getCurrentPersonnel()) {
동시성 이슈에 대해 말씀을 드린 건 맞습니다 ~ 그걸 안나도록 하는게 동시성 제어구요!

2024-11-10 13:49 UTC, f-lab-moony commented on src/main/java/yeogi/moim/participant/service/ParticipantService.java
> +    public ParticipantResponse registerMemberParticipant(ParticipantRequest participantRequest) {
`joinGatheringForMember` 요녀석 말씀드렸습니다!

2024-11-15 17:11 UTC, Kimjipang commented on src/main/java/yeogi/moim/gathering/service/GatheringService.java
> +    public Gathering registerGathering(GatheringRequest gatheringRequest, Long gatheringOwnerId) {
멘토님 기존에 RegisterGatheringService 내에서 Gathering 객체를 직접 생성하던 부분을 수정한 것인데요 !

RegisterGatheringService 내에서 Gathering 객체를 생성한 후에 모임 생성자를 Leader로 하는 Participant 객체를 생성할 때, 모임의 PK가 필요해서 registerGathering의 반환 타입을 Gathering 으로 했는데, 이런 방식으로 하는 것 괜찮나요?

2024-11-15 17:51 UTC, Kimjipang commented on src/main/java/yeogi/moim/gathering/dto/SearchGatheringRequest.java
> +    private Category category;
멘토님 아직 push는 안 했는데요, 이번주 수요일 멘토링 전에 작성해 두었던 코드 내용이 아래와 같은 방식입니다.

정렬 조건이 3가지(제목순, 현재 인원순, 생성일순)일때, 제목(1순위 정렬 기준)이 동일하면, 현재 인원순(2순위)을 기준으로 정렬하는 방식이거든요 ! 

근데, 멘토님이 말씀하신 것은 3가지 중에 1개만으로만 정렬 기준을 선택하는 것이었는데요! 제가 작성한 방식이랑 비교해서 어떤 방식이 나을까요?

2024-11-19 12:07 UTC, f-lab-moony commented on src/main/java/yeogi/moim/gathering/dto/SearchGatheringRequest.java
> +    private Category category;
뭐가 나은지보다는 서비스에서 어떻게 결정해야할지를 생각해봐야 할 것 같아요 ~
말씀하신 내용은 사용자가 선택하는게 아니라 정렬 방식이 정해져있는거라 정책으로 만들면 아예 다른얘기가 될 것 같구요
제가 말씀드린건 사실 1개만 정렬 기준이 된다기보단 정렬의 종류가 1개씩 골라지는거였는데요, 이렇게 다 고려하면 로직이 복잡해져서 하나만 말씀드리긴 했습니다.

보통 서비스에서는 말씀하신것처럼 정렬 방식을 하나 정해서 기본값으로 설정하고, 사용자가 선택할 수 있는 정렬 방식들이 따로 있을거라 선택을 할 수 있게 해주시는게 좋을 것 같습니다!

2024-11-19 12:09 UTC, f-lab-moony commented on src/main/java/yeogi/moim/gathering/service/GatheringService.java
> +    public Gathering registerGathering(GatheringRequest gatheringRequest, Long gatheringOwnerId) {
Facade에서 편의를 위해 리턴타입을 엔티티 그대로 받으면 좋은 경우들이 있긴 한데요, 일단 public으로 뚫리는거라 별로 권장되는 방법은 아닙니다.

근데 Response에 id 어차피 넣어줘야할텐데 굳이 pk때문에 엔티티를 반환 할 이유가 있나요 ?

2024-11-19 12:10 UTC, f-lab-moony reviewed
이거 혹시 작업이 다 되신걸까요 ? 변경사항이 Facade 적용밖에 안보여서 여쭤봐요 ~

2024-11-20 15:36 UTC, f-lab-moony approved these changes
좋아요랑 리뷰가 간단하게 구현돼있어서 몇개만 피드백 남겼는데요!
이거 근데 기존에 하려던 기능이랑은 또 다른거같아서 여기서 진행하는게 안맞는 것 같아요
이후 작업은 이슈 새로 등록해서 진행 해 주세요 ~
이번 PR은 머지 해둘게요
고생 많으셨습니다 ~

2024-11-20 15:36 UTC, f-lab-moony commented on src/main/java/yeogi/moim/favorite/service/FavoriteService.java
> +            throw new IllegalArgumentException("이미 좋아요 누른 모임입니다.");
좋아요 기능은 보통 토글로 만들어서, 이렇게 해도 상관은 없지만 요청 시 플래그를 바꾸는 방식으로도 한번 고민해보면 좋을 것 같네요!

2024-11-20 15:36 UTC, f-lab-moony commented on src/main/java/yeogi/moim/favorite/service/FavoriteService.java
> +        favoriteRepository.save(favorite);
좋아요 같은 기능은 상대적으로 접근이 쉽게 되어있어서, 매번 등록, 삭제 하기보단 플래그를 두고 업데이트를 하는게 낫지 않을까요 ?

2024-11-20 15:36 UTC, f-lab-moony commented on src/main/java/yeogi/moim/favorite/service/FavoriteService.java
> +    public List<FavoriteResponse> getFavoriteList() {
요거 응답은 FavoriteResponse의 컬렉션보다 FavoriteResponse가 gathering 리스트를 갖고 있는게 낫지 않을까요 ?

2024-11-20 15:36 UTC, merged

2024-11-20 15:53 UTC, Kimjipang commented on src/main/java/yeogi/moim/favorite/service/FavoriteService.java
> +            throw new IllegalArgumentException("이미 좋아요 누른 모임입니다.");
넵 :) 반영해보겠습니다 !

2024-11-20 15:54 UTC, Kimjipang commented on src/main/java/yeogi/moim/favorite/service/FavoriteService.java
> +        favoriteRepository.save(favorite);
넵!! 반영해보겠습니당~!

2024-11-20 15:56 UTC, Kimjipang commented on src/main/java/yeogi/moim/favorite/service/FavoriteService.java
> +    public List<FavoriteResponse> getFavoriteList() {
`getFavoriteList()`의 목적이 좋아요를 누른 모임을 반환하는 것이니까 FavoriteResponse에서 gathering을 포함하는 것이 낫지 않겠냐는 말씀이신가요?