Feature/issue 7
f-lab-edu/yeogi-moim pull request #9
Opened 2024-11-21 09:47 UTC by Kimjipang

2024-11-24 14:45 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백 확인 부탁드려요 ~

2024-11-24 14:45 UTC, f-lab-moony commented on src/main/java/yeogi/moim/favorite/service/FavoriteService.java
> +            favoriteRepository.delete(favorite);
요거 저번에 피드백 남겼던 것 같은데
좋아요라는 기능 특성상 좋아요 했다가 취소했다가 하는게 굉장히 자유로울 것 같아요
이걸 save / delete 하는걸로 설계를 하면 성능에 어떤 영향이 생길까요 ?

2024-11-24 14:45 UTC, f-lab-moony commented on src/main/java/yeogi/moim/favorite/service/FavoriteService.java
> +                    GatheringResponse gatheringResponse = gatheringService.getGathering(favorite.getGatheringId());
stream API의 장점은 선언형 프로그래밍을 하면서 가독성을 높일 수 있다는 데 있는데요, 이렇게 동작을 다 드러내면 그 장점이 퇴색될 수 있어요. 메서드 분리를 통해 무엇을 하는지를 더 드러내 볼 수 있으면 좋을 것 같아요 ~

2024-11-26 04:04 UTC, Kimjipang commented on src/main/java/yeogi/moim/favorite/service/FavoriteService.java
> +            favoriteRepository.delete(favorite);
토글 방식을 구현해보고자 좋아요가 눌려져 있으면 좋아요를 삭제하는 것으로 하고, 반대로 좋아요가 없으면 좋아요가 반영되게끔 구현하고자 했는데, 이렇게 설계가 되면 DB 작업을 너무 많이 하게 될 거 같습니다 !

다른 방법으로 해보겠습니다~!

2024-11-26 04:04 UTC, Kimjipang commented on src/main/java/yeogi/moim/favorite/service/FavoriteService.java
> +                    GatheringResponse gatheringResponse = gatheringService.getGathering(favorite.getGatheringId());
한 번 해보겠습니다 !

2024-11-27 12:42 UTC, f-lab-moony requested changes
고생하셨습니다 ~ 피드백 확인 해주세요 ~

2024-11-27 12:42 UTC, f-lab-moony commented on src/main/java/yeogi/moim/favorite/service/FavoriteService.java
> +        GatheringResponse gatheringResponse = gatheringService.getGathering(favorite.getGatheringId());
getGathering을 할 때 select 쿼리가 user가 좋아요를 누른 게시글 수만큼 실행 될 것 같은데, 어떻게 개선할 수 있을까요 ?

2024-11-27 12:42 UTC, f-lab-moony commented on src/main/java/yeogi/moim/favorite/service/FavoriteService.java
> +            favorite.toggleFavorite();
save / toggle 하는 조건이 반대가 되어야 하지 않을까요 ?

2024-11-27 12:42 UTC, f-lab-moony commented on src/main/java/yeogi/moim/favorite/dto/FavoriteResponse.java
> +                .isFavorite(favorite.getIsFavorite())
좋아요 상태가 관리되는거라면 id는 이제 필요 없지 않을까요 ?

2024-12-10 12:40 UTC, f-lab-moony approved these changes
고생 많으셨습니다 ~
이번 PR은 머지 하도록 할게요!

2024-12-10 12:40 UTC, f-lab-moony commented on src/main/java/yeogi/moim/favorite/service/FavoriteService.java
> +                .map(favorite -> {
요런거 최대한 메서드 분리를 하는 습관을 들이면 좋을 것 같아요 ~

2024-12-10 12:40 UTC, f-lab-moony commented on src/main/java/yeogi/moim/favorite/repository/FavoriteRepositoryCustomImpl.java
> +    public List<FavoriteResponse> findByUserIdWithGathering(Long userId) {
좋아요를 누른 모임 목록이면 그냥 Gathering으로 반환이 되어도 될 것 같은데, 이 응답은 어디서 활용되는 걸 생각하신걸까요 ?

2024-12-10 12:41 UTC, merged